version: '3.8'

services:
  service-a:
    build: ./service-a
    networks:
      - kong-net
    ports:
      - "3001:3001" # Ajout du mappage de port pour service-a

  service-b:
    build: ./service-b
    networks:
      - kong-net
    ports:
      - "3002:3002" # Ajout du mappage de port pour service-b

  kong:
    image: kong:latest
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
    volumes:
      - ./kong.yml:/etc/kong/kong.yml:ro
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
      - kong-net

networks:
  kong-net:
    driver: bridge